#####################################
### "BANCO DE DADOS SUPERMERCADO" ###
#####################################

CREATE DATABASE IF NOT EXISTS db_supermercado; # CRIAR BANCO DE DADOS "SUPERMERCADO", CASO ELE JÁ NÃO EXISTA
USE db_supermercado; # USAR BANCO DE DADOS

-- OBSERVAÇÃO: NO MODELO CONCEITUAL E LÓGICO, EU CRIEI TABELAS SEPARADAS PARA O DADO "ENUM", 
-- POIS A OPÇÃO DE POR ENUM NO BRMODELO NÃO EXISTE, POREM AQUI ESTAREI USANDO ESTE TIPO DE DADO

#####################################
-- "CRIAÇÃO DAS TABELAS"
#####################################

-- 1. TABELA CLIENTES
CREATE TABLE tbl_clientes (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR ÚNICO DO CLIENTE
	nome_completo VARCHAR(150) NOT NULL, -- NOME COMPLETO DO CLIENTE
	cpf CHAR(11) UNIQUE NOT NULL, -- CPF OBRIGATÓRIO DO CLIENTE
	cnpj CHAR(14) , -- CPF OPCIONAL (PARA EMPRESAS)
	telefone VARCHAR(20) NOT NULL, -- TELEFONE PARA CONTATO
    email VARCHAR(150), -- EMAIL OPCIONAL
    rua VARCHAR(150) NOT NULL, -- ENDEREÇO: RUA
    numero VARCHAR(20) NOT NULL, -- NUMERO DO ENDEREÇO
    bairro VARCHAR(100) NOT NULL, -- BAIRRO
    cidade VARCHAR(100) NOT NULL, -- CIDADE
    estado CHAR(2) NOT NULL, -- ESTADO (UF)
    cep CHAR(8) NOT NULL, -- CEP
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP, -- DATA DE CRIAÇÃO AUTOMÁTICA
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- ATUALIZAÇÃO AUTOMÁTICA
    PRIMARY KEY (id)
);

-- 2. TABELA FUNCIONÁRIOS
CREATE TABLE tbl_funcionarios (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR DO FUNCIONÁRIO
    nome VARCHAR(150) NOT NULL, -- NOME COMPLETO
    matricula VARCHAR(30) UNIQUE NOT NULL, -- MATRÍCULA ÚNICA
    cargo VARCHAR(150) NOT NULL, -- CARGO OCUPADO NA EMPRESA
    email VARCHAR(150) NOT NULL, -- EMAIL CORPORATIVO
    login VARCHAR(50) UNIQUE NOT NULL, -- LOGIN ÚNICO DO SISTEMA
    senha_hash VARCHAR(255) NOT NULL, -- SENHA CRIPTOGRAFADA
    nivel_acesso ENUM ('OPERADOR', 'GERENTE', 'ADMIN') NOT NULL, -- NÍVEL DE PERMISSÃO
    ativo TINYINT(1) DEFAULT 1 NOT NULL, -- STATUS DO FUNCIONÁRIO (ATIVO/INATIVO)
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- 3. TABELA CATEGORIAS
CREATE TABLE tbl_categorias (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR ÚNICO DA CATEGORIA
    nome VARCHAR(100) NOT NULL, -- NOME DA CATEGORIA
    descricao VARCHAR(255) NOT NULL, -- DESCRIÇÃO
    ativo TINYINT(1) DEFAULT 1 NOT NULL, -- INDICA SE A CATEGORIA ESTÁ ATIVA
    PRIMARY KEY (id)
); 

-- 4. TABELA PRODUTOS
CREATE TABLE tbl_produtos (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DO PRODUTO
    id_categoria INT UNSIGNED NOT NULL, -- REFEÊNCIA À CATEGORIA
    sku VARCHAR(50) UNIQUE NOT NULL, -- CÓDIGO SKU ÚNICO
    nome VARCHAR(150) NOT NULL, -- NOME DO PRODUTO
    descricao TEXT NOT NULL, -- DESCRIÇÃO COMPLETA DO PRODUTO
    ean VARCHAR(20) NOT NULL, -- CÓDIGO DE BARRAS 
    preco_custo DECIMAL(10,2) NOT NULL, -- VALOR DE CUSTO
    preco_venda DECIMAL(10,2) NOT NULL, -- VALOR DE VENDA
    quantidade_estoque DECIMAL(10,3) DEFAULT 0 NOT NULL, -- QUANTIDADE EM ESTOQUE
    unidade ENUM ('UN','KG', 'L') NOT NULL, -- UNIDADE DE VENDA
    validade DATE NOT NULL, -- DATA DE VALIDADE
    ativo TINYINT(1) DEFAULT 1 NOT NULL, -- STATUS DO PRODUTO ATIVO/INATIVO
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    
    CONSTRAINT FK_Produto_Categoria
		FOREIGN KEY (id_categoria) REFERENCES tbl_categorias(id) -- RELACIONAMENTO PRODUTO → CATEGORIA
);

-- 5. TABELA VENDAS
CREATE TABLE tbl_vendas (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DA VENDA
    id_cliente INT UNSIGNED NOT NULL, -- CLIENTE QUE REALIZOU A COMPRA
    id_funcionario INT UNSIGNED NOT NULL, -- FUNCIONÁRIO QUE REGISTROU A COMPRA
    data_hora DATETIME NOT NULL, -- DATA E HORA DA VENDA
    observacao VARCHAR (255), -- OBSERVAÇÕES OPCIONAIS
    pontos_gerados INT(10) DEFAULT 0, -- PONTOS GANHOS PELO CLIENTE
    pontos_utilizados INT(10) DEFAULT 0, -- PONTOS UTILIZADOS NA COMPRA PELO CLIENTE
    valor_total DECIMAL(10,2) NOT NULL, -- VALOR TOTAL DA VENDA
    numero_documento_fiscal VARCHAR(50) NOT NULL, -- NOTA FISCAL
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    
    CONSTRAINT FK_Venda_Cliente
		FOREIGN KEY (id_cliente) REFERENCES tbl_clientes(id), -- RELACIONAMENTO VENDA → CLIENTE
        
	CONSTRAINT FK_Venda_Funcionario
		FOREIGN KEY (id_funcionario) REFERENCES tbl_funcionarios(id) -- RELACIONAMENTO VENDA → FUNCIONÁRIO
);

-- 6. TABELA ITENS VENDA
CREATE TABLE tbl_itens_venda (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DO ITEM DA VENDA
    id_venda INT UNSIGNED NOT NULL, -- REFERÊNCIA A VENDA
    id_produto INT UNSIGNED NOT NULL, -- REFERÊNCIA AO PRODUTO
    quantidade DECIMAL(10,3) NOT NULL, -- QUANTIDADE VENDIDA
    preco_unitario DECIMAL(10,2) NOT NULL, -- PREÇO NA HORA DA VENDA
    preco_total DECIMAL(10,2)NOT NULL, -- SUBTOTAL
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    
    CONSTRAINT FK_ItensVenda_Venda
		FOREIGN KEY (id_venda) REFERENCES tbl_vendas(id), -- RELACIONAMENTO ITENS VENDA → VENDAS
        
	CONSTRAINT FK_ItensVenda_Produto
		FOREIGN KEY (id_produto) REFERENCES tbl_produtos(id) -- RELACIONAMENTO ITENS VENDA → PRODUTOS
);

-- 7. TABELA PONTOS MOVIMENTAÇÕES
CREATE TABLE tbl_pontos_movimentacoes (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DA MOVIMENTAÇÃO DE PONTOS
	id_cliente INT UNSIGNED NOT NULL, -- CLIENTE DONO DOS PONTOS
    id_venda INT UNSIGNED NOT NULL, -- RELACIONADO A UMA VENDA
	pontos INT(11) NOT NULL, -- QUANTIDADE DE PONTOS
	tipo ENUM('CREDITO', 'DEBITO') NOT NULL, -- ENTRADA OU SAÍDA DE PONTOS
    descricao VARCHAR(255), -- DESCRIÇÃO DA MOVIMENTAÇÃO
    data_hora DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    
    CONSTRAINT FK_Pontos_Cliente
		FOREIGN KEY (id_cliente) REFERENCES tbl_clientes(id), -- RELACIONAMENTO PONTOS MOVIMENTAÇÃO → CLIENTES
    
    CONSTRAINT FK_Pontos_Venda
		FOREIGN KEY (id_venda) REFERENCES tbl_vendas(id) -- RELACIONAMENTO PONTOS MOVIMENTAÇÃO → VENDAS
);

-- 8. TABELA PAGAMENTOS
CREATE TABLE tbl_pagamentos (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DO PAGAMENTO
    id_venda INT UNSIGNED NOT NULL, -- VENDA QUE RECEBEU PAGAMENTO
    valor DECIMAL (10,2) NOT NULL, -- VALOR A PAGAR
    tipo ENUM ('DINHEIRO', 'CARTAO', 'PIX', 'OUTROS') NOT NULL, -- FORMA DE PAGAMENTO
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    
    CONSTRAINT FK_Pagamento_Venda
		FOREIGN KEY (id_venda) REFERENCES tbl_vendas(id) -- RELACIONAMENTO PAGAMENTOS → VENDAS
); 

-- 9. TABELA PROMOÇÕES
CREATE TABLE tbl_promocoes (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DA PROMOÇÃO
	id_produto INT UNSIGNED NOT NULL, -- PRODUTO QUE RECEBEU PROMOÇÃO
	preco_promocional DECIMAL(10,2) NOT NULL, -- PREÇO PROMOCIONAL
	data_inicio DATETIME, -- INÍCIO DA PROMOÇÃO
	data_fim DATETIME, -- FIM DA PROMOÇÃO
	ativo TINYINT(1) DEFAULT 1 NOT NULL, -- PROMOÇÃO ATIVA OU INATIVA
	criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
    
    CONSTRAINT FK_Promocao_Produto
		FOREIGN KEY (id_produto) REFERENCES tbl_produtos(id) -- RELACIONAMENTO PROMOÇÃO → PRODUTO
);
    
-- 10. TABELA ESTOQUE MOVIMENTOS
CREATE TABLE tbl_estoque_movimento (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DA MOVIMENTAÇÃO
	id_produto INT UNSIGNED NOT NULL, -- PRODUTO MOVIMENTADO
	id_funcionario INT UNSIGNED NOT NULL, -- FUNCIONÁRIO RESPONSÁVEL
	tipo ENUM ('VENDA','PERDA','AJUSTE') NOT NULL, -- TIPO DA MOVIMENTAÇÃO
	quantidade DECIMAL(10,3) NOT NULL, -- QUANTIDADE MOVIMENTADA
	referencia VARCHAR(100) NOT NULL, -- REFERÊNCIA EXTERNA (EXEMPLO: ID DA VENDA)
	motivo VARCHAR(255) NOT NULL, -- MOTIVO DA MOVIMENTAÇÃO
	data_hora DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
    
    CONSTRAINT FK_Movimento_Produto
		FOREIGN KEY (id_produto) REFERENCES tbl_produtos(id), -- RELACIONAMENTO ESTOQUE MOVIMENTO → PRODUTO
    
    CONSTRAINT FK_Movimento_Funcionario
		FOREIGN KEY (id_funcionario) REFERENCES tbl_funcionarios(id) -- RELACIONAMENTO ESTOQUE MOVIMENTO → FUNCIONÁRIO
);
    
-- 11. TABELA HISTÓRICO LOGS
CREATE TABLE tbl_historico_logs (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, -- ID DA LOG
    id_funcionario INT UNSIGNED NOT NULL, -- FUNCIONÁRIO QUE EXECUTOU A AÇÃO
    acao ENUM ('ATUALIZAR', 'DELETAR', 'LOGIN', 'OUTROS') NOT NULL, -- TIPO DE AÇÃO REGISTRADA
    tabela_afetada VARCHAR(100) NOT NULL, -- TABELA ONDE OCORREU A AÇÃO
    registro_id BIGINT(20) NOT NULL, -- ID DO REGISTRO AFETADO
    descricao TEXT NOT NULL, -- DETALHES DA AÇÃO/EVENTO
    data_hora DATETIME DEFAULT CURRENT_TIMESTAMP, -- DATA DA AÇÃO
    PRIMARY KEY (id),
    
    CONSTRAINT FK_Log_Funcionario
		FOREIGN KEY (id_funcionario) REFERENCES tbl_funcionarios(id) -- RELACIONAMENTO HISTÓRICO → FUNCIONÁRIO
); 
